local C = {}

C.VIRTUAL_W = 800
C.VIRTUAL_H = 600

C.WALL_THICKNESS = 16
C.PLAY_MIN_X = C.WALL_THICKNESS
C.PLAY_MIN_Y = C.WALL_THICKNESS
C.PLAY_MAX_Y = C.VIRTUAL_H - C.WALL_THICKNESS
C.PLAY_MAX_X = C.VIRTUAL_W - C.WALL_THICKNESS

C.STATE = {
	MENU = "menu",
	PLAYING = "playing",
	PAUSED = "paused",
	WIN = "win",
	LOSE = "lose",
}
C.HAMMY_WIDTH = 40
C.HAMMY_HEIGHT = 40
C.HAMMY_SPEED = 200
C.HAMMY_DISPLAY_SCALE = 3

C.SNACK_MIN = 3
C.SNACK_MAX = 8
C.SNACK_SIZE = 20
C.SNACK_DISPLAY_SCALE = 1

C.VACUUM_WIDTH = 50
C.VACUUM_HEIGHT = 50
C.VACUUM_DISPLAY_SCALE = 2
C.VACUUM_SPEED_SWEEP = 50
C.VACUUM_SPEED_CHASE = 175
C.VACUUM_DETECTION_RADIUS = 150
C.VACUUM_FLIP_INTERVAL = 1.0
C.VACUUM_STATE = {
	SWEEPING = "sweeping",
	CHASING = "chasing",
}

C.OBSTACLE_SIZE = 50

C.OBJECT_TAGS = {
	WALL = "wall",
	OBSTACLE = "obstacle",
	DOOR = "door",
}

C.DOOR_SIZE = 40
C.DOOR_POSITION = {
	RIGHT = "right",
	LEFT = "left",
	TOP = "top",
	BOTTOM = "bottom",
}

C.DEBUG = false

return C
